-- 0008 — identity-колонки
-- Порождается из каталога эталонной базы; см. db/README.md.

-- analytics.anomaly_analysis_revision_id_seq
ALTER TABLE analytics.anomaly_analysis_revision ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME analytics.anomaly_analysis_revision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- analytics.dataset_revision_id_seq
ALTER TABLE analytics.dataset_revision ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME analytics.dataset_revision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- analytics.institution_daily_metrics_id_seq
ALTER TABLE analytics.institution_daily_metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME analytics.institution_daily_metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- analytics.institution_metric_aggregate_id_seq
ALTER TABLE analytics.institution_metric_aggregate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME analytics.institution_metric_aggregate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- analytics.institution_monthly_metrics_id_seq
ALTER TABLE analytics.institution_monthly_metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME analytics.institution_monthly_metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- analytics.institution_period_metrics_id_seq
ALTER TABLE analytics.institution_period_metrics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME analytics.institution_period_metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- catalog.account_external_identity_id_seq
ALTER TABLE catalog.account_external_identity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME catalog.account_external_identity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- catalog.account_identity_history_id_seq
ALTER TABLE catalog.account_identity_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME catalog.account_identity_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- catalog.legacy_alias_channels_seq
CREATE SEQUENCE catalog.legacy_alias_channels_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- catalog.legacy_alias_institutions_seq
CREATE SEQUENCE catalog.legacy_alias_institutions_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- catalog.legacy_alias_platform_accounts_seq
CREATE SEQUENCE catalog.legacy_alias_platform_accounts_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- catalog.legacy_alias_platform_posts_seq
CREATE SEQUENCE catalog.legacy_alias_platform_posts_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- catalog.legacy_alias_posts_seq
CREATE SEQUENCE catalog.legacy_alias_posts_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- ingest.account_metric_snapshot_id_seq
ALTER TABLE ingest.account_metric_snapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ingest.account_metric_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ingest.collection_account_result_id_seq
ALTER TABLE ingest.collection_account_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ingest.collection_account_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ingest.deletion_observation_id_seq
ALTER TABLE ingest.deletion_observation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ingest.deletion_observation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ingest.metric_evidence_dictionary_id_seq
ALTER TABLE ingest.metric_evidence_dictionary ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME ingest.metric_evidence_dictionary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ingest.publication_identity_id_seq
ALTER TABLE ingest.publication_identity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ingest.publication_identity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ingest.publication_metric_snapshot_id_seq
ALTER TABLE ingest.publication_metric_snapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ingest.publication_metric_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- ops_and_admin.outbox_event_id_seq
ALTER TABLE ops_and_admin.outbox_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ops_and_admin.outbox_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- rating.rating_component_result_id_seq
ALTER TABLE rating.rating_component_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME rating.rating_component_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
