-- 0017 — права ролей
-- Порождается из каталога эталонной базы; см. db/README.md.
-- Права на партиции наследуются от родительской таблицы и отдельно не выдаются.

-- analytics_worker (16)
GRANT USAGE ON SCHEMA analytics TO analytics_worker;
GRANT USAGE ON SCHEMA catalog TO analytics_worker;
GRANT USAGE ON SCHEMA ingest TO analytics_worker;
GRANT USAGE ON SCHEMA ops_and_admin TO analytics_worker;
GRANT ALL ON FUNCTION analytics.anomaly_input_is_unchanged(p_publication_id uuid, p_input_hash text, p_manifest_hash text) TO analytics_worker;
GRANT ALL ON FUNCTION analytics.anomaly_operational_metrics() TO analytics_worker;
GRANT ALL ON FUNCTION analytics.extract_publication_history_as_of(p_publication_ids uuid[], p_source_dataset_revision bigint, p_max_points integer) TO analytics_worker;
GRANT SELECT ON TABLE ingest.metric_evidence_dictionary TO analytics_worker;
GRANT SELECT ON TABLE ingest.publication_metric_snapshot_resolved TO analytics_worker;
GRANT ALL ON FUNCTION analytics.publication_snapshot_slice(p_publication uuid, p_month date) TO analytics_worker;
GRANT ALL ON FUNCTION analytics.publish_anomaly_failure(p_publication_id uuid, p_claim_token uuid, p_generation bigint, p_attempt_key uuid, p_source_revision bigint, p_manifest_hash text, p_preprocessor text, p_aggregator text, p_semantic_version integer, p_capability_version integer, p_started_at timestamp with time zone, p_error_code text, p_retry_seconds integer) TO analytics_worker;
GRANT ALL ON FUNCTION analytics.publish_anomaly_success(p_publication_id uuid, p_claim_token uuid, p_generation bigint, p_attempt_key uuid, p_source_revision bigint, p_input_hash text, p_manifest_hash text, p_preprocessor text, p_aggregator text, p_semantic_version integer, p_capability_version integer, p_started_at timestamp with time zone, p_status text, p_score numeric, p_severity text, p_findings jsonb) TO analytics_worker;
GRANT ALL ON FUNCTION ops_and_admin.claim_anomaly_candidates(p_limit integer, p_lease_seconds integer, p_claim_token uuid) TO analytics_worker;
GRANT ALL ON FUNCTION ops_and_admin.complete_anomaly_noop(p_publication_id uuid, p_claim_token uuid, p_generation bigint) TO analytics_worker;
GRANT ALL ON FUNCTION ops_and_admin.pin_latest_anomaly_source_revision() TO analytics_worker;
GRANT ALL ON FUNCTION ops_and_admin.seed_anomaly_backfill(p_limit integer, p_manifest_hash text) TO analytics_worker;

-- api_read (62)
GRANT USAGE ON SCHEMA analytics TO api_read;
GRANT USAGE ON SCHEMA catalog TO api_read;
GRANT USAGE ON SCHEMA ingest TO api_read;
GRANT USAGE ON SCHEMA ops_and_admin TO api_read;
GRANT USAGE ON SCHEMA rating TO api_read;
GRANT ALL ON FUNCTION analytics.observation_quality_from_rank(p_rank integer) TO api_read;
GRANT ALL ON FUNCTION analytics.observation_quality_rank(p_quality ingest.observation_quality) TO api_read;
GRANT ALL ON FUNCTION analytics.ordered_history_reactions(p_text text, p_signed boolean) TO api_read;
GRANT SELECT ON TABLE catalog.institution TO api_read;
GRANT SELECT ON TABLE catalog.platform_account TO api_read;
GRANT SELECT ON TABLE catalog.visible_institution TO api_read;
GRANT SELECT ON TABLE catalog.visible_platform_account TO api_read;
GRANT SELECT ON TABLE ingest.metric_evidence_dictionary TO api_read;
GRANT SELECT ON TABLE ingest.publication TO api_read;
GRANT SELECT ON TABLE ingest.publication_metric_snapshot_resolved TO api_read;
GRANT SELECT ON TABLE ingest.visible_publication TO api_read;
GRANT SELECT ON TABLE analytics.usable_publication_snapshot TO api_read;
GRANT ALL ON FUNCTION analytics.publication_snapshot_slice(p_publication uuid, p_month date) TO api_read;
GRANT ALL ON FUNCTION ops_and_admin.public_health_snapshot() TO api_read;
GRANT SELECT ON TABLE analytics.account_latest TO api_read;
GRANT SELECT ON TABLE analytics.anomaly_event TO api_read;
GRANT SELECT ON TABLE analytics.anomaly_review TO api_read;
GRANT SELECT ON TABLE analytics.comparison_cohort TO api_read;
GRANT SELECT ON TABLE analytics.comparison_cohort_member TO api_read;
GRANT SELECT ON TABLE analytics.dataset_revision TO api_read;
GRANT SELECT ON TABLE analytics.institution_daily_metrics TO api_read;
GRANT SELECT ON TABLE analytics.institution_metric_aggregate TO api_read;
GRANT SELECT ON TABLE analytics.institution_monthly_metrics TO api_read;
GRANT SELECT ON TABLE analytics.institution_period_metrics TO api_read;
GRANT SELECT ON TABLE analytics.legacy_overview_account TO api_read;
GRANT SELECT ON TABLE analytics.legacy_overview_card TO api_read;
GRANT SELECT ON TABLE analytics.metric_semantic_definition TO api_read;
GRANT SELECT ON TABLE analytics.platform_metric_capability TO api_read;
GRANT SELECT ON TABLE analytics.publication_analysis_state_public TO api_read;
GRANT SELECT ON TABLE analytics.publication_anomaly_finding_public TO api_read;
GRANT SELECT ON TABLE analytics.publication_content TO api_read;
GRANT SELECT ON TABLE analytics.publication_history TO api_read;
GRANT SELECT ON TABLE analytics.publication_latest TO api_read;
GRANT SELECT ON TABLE catalog.account_external_identity TO api_read;
GRANT SELECT ON TABLE catalog.account_identity_history TO api_read;
GRANT SELECT ON TABLE catalog.account_verification TO api_read;
GRANT SELECT ON TABLE catalog.institution_external_id TO api_read;
GRANT SELECT ON TABLE catalog.legacy_entity_alias TO api_read;
GRANT SELECT ON TABLE ingest.account_metric_snapshot_active TO api_read;
GRANT SELECT ON TABLE ingest.collection_account_result TO api_read;
GRANT SELECT ON TABLE ingest.collection_run TO api_read;
GRANT SELECT(id) ON TABLE ingest.publication_identity TO api_read;
GRANT SELECT(publication_id) ON TABLE ingest.publication_identity TO api_read;
GRANT SELECT(external_id) ON TABLE ingest.publication_identity TO api_read;
GRANT SELECT(role) ON TABLE ingest.publication_identity TO api_read;
GRANT SELECT(public_url) ON TABLE ingest.publication_identity TO api_read;
GRANT SELECT ON TABLE ingest.reaction_breakdown TO api_read;
GRANT SELECT ON TABLE ops_and_admin.schema_contract TO api_read;
GRANT SELECT ON TABLE rating.formula_component TO api_read;
GRANT SELECT ON TABLE rating.formula_definition TO api_read;
GRANT SELECT ON TABLE rating.official_account_rating_observation TO api_read;
GRANT SELECT ON TABLE rating.official_rating_observation TO api_read;
GRANT SELECT ON TABLE rating.official_institution_rating_observation TO api_read;
GRANT SELECT ON TABLE rating.population_observation TO api_read;
GRANT SELECT ON TABLE rating.rating_component_result TO api_read;
GRANT SELECT ON TABLE rating.rating_result TO api_read;
GRANT SELECT ON TABLE rating.rating_run TO api_read;

-- api_write_admin (54)
GRANT USAGE ON SCHEMA analytics TO api_write_admin;
GRANT USAGE ON SCHEMA catalog TO api_write_admin;
GRANT USAGE ON SCHEMA ingest TO api_write_admin;
GRANT USAGE ON SCHEMA ops_and_admin TO api_write_admin;
GRANT USAGE ON SCHEMA rating TO api_write_admin;
GRANT ALL ON FUNCTION analytics.append_anomaly_review(p_finding_id uuid, p_decision text, p_private_comment text, p_subject text, p_correlation_id uuid, p_idempotency_key uuid, p_request_digest text) TO api_write_admin;
GRANT ALL ON FUNCTION analytics.create_manual_anomaly_signal(p_publication_id uuid, p_metric text, p_severity text, p_explanation_code text, p_start_at timestamp with time zone, p_end_at timestamp with time zone, p_evidence jsonb, p_subject text, p_correlation_id uuid, p_idempotency_key uuid, p_request_digest text) TO api_write_admin;
GRANT INSERT,UPDATE ON TABLE catalog.institution TO api_write_admin;
GRANT INSERT,UPDATE ON TABLE catalog.platform_account TO api_write_admin;
GRANT SELECT ON TABLE catalog.visible_institution TO api_write_admin;
GRANT SELECT ON TABLE catalog.visible_platform_account TO api_write_admin;
GRANT SELECT ON TABLE ingest.visible_publication TO api_write_admin;
GRANT ALL ON FUNCTION ops_and_admin.catalog_command(p_action text, p_target uuid, p_expected bigint, p_body jsonb, p_actor text, p_correlation uuid) TO api_write_admin;
GRANT ALL ON FUNCTION ops_and_admin.import_official_rating(p_payload jsonb, p_actor text, p_correlation uuid) TO api_write_admin;
GRANT ALL ON FUNCTION ops_and_admin.legacy_account_presentation(p_account uuid) TO api_write_admin;
GRANT ALL ON FUNCTION ops_and_admin.previous_official_rating(p_actor text, p_correlation uuid) TO api_write_admin;
GRANT SELECT ON TABLE analytics.account_latest TO api_write_admin;
GRANT INSERT ON TABLE analytics.anomaly_review TO api_write_admin;
GRANT INSERT ON TABLE analytics.dataset_revision TO api_write_admin;
GRANT SELECT,USAGE ON SEQUENCE analytics.dataset_revision_id_seq TO api_write_admin;
GRANT SELECT,USAGE ON SEQUENCE analytics.institution_daily_metrics_id_seq TO api_write_admin;
GRANT SELECT,USAGE ON SEQUENCE analytics.institution_metric_aggregate_id_seq TO api_write_admin;
GRANT SELECT,USAGE ON SEQUENCE analytics.institution_monthly_metrics_id_seq TO api_write_admin;
GRANT SELECT,USAGE ON SEQUENCE analytics.institution_period_metrics_id_seq TO api_write_admin;
GRANT SELECT ON TABLE analytics.publication_content TO api_write_admin;
GRANT SELECT ON TABLE analytics.publication_history TO api_write_admin;
GRANT INSERT,UPDATE ON TABLE catalog.account_external_identity TO api_write_admin;
GRANT SELECT,USAGE ON SEQUENCE catalog.account_external_identity_id_seq TO api_write_admin;
GRANT INSERT,UPDATE ON TABLE catalog.account_identity_history TO api_write_admin;
GRANT SELECT,USAGE ON SEQUENCE catalog.account_identity_history_id_seq TO api_write_admin;
GRANT INSERT,DELETE,UPDATE ON TABLE catalog.account_verification TO api_write_admin;
GRANT INSERT,DELETE,UPDATE ON TABLE catalog.institution_external_id TO api_write_admin;
GRANT INSERT,UPDATE ON TABLE catalog.legacy_entity_alias TO api_write_admin;
GRANT SELECT ON TABLE ingest.collection_account_result TO api_write_admin;
GRANT SELECT ON TABLE ingest.collection_run TO api_write_admin;
GRANT INSERT ON TABLE ops_and_admin.audit_log TO api_write_admin;
GRANT SELECT,INSERT,UPDATE ON TABLE ops_and_admin.operational_checkpoint TO api_write_admin;
GRANT SELECT,INSERT ON TABLE ops_and_admin.outbox_event TO api_write_admin;
GRANT UPDATE(available_at) ON TABLE ops_and_admin.outbox_event TO api_write_admin;
GRANT UPDATE(published_at) ON TABLE ops_and_admin.outbox_event TO api_write_admin;
GRANT UPDATE(publish_attempts) ON TABLE ops_and_admin.outbox_event TO api_write_admin;
GRANT UPDATE(last_error_code) ON TABLE ops_and_admin.outbox_event TO api_write_admin;
GRANT SELECT,USAGE ON SEQUENCE ops_and_admin.outbox_event_id_seq TO api_write_admin;
GRANT SELECT ON TABLE ops_and_admin.schema_contract TO api_write_admin;
GRANT INSERT,UPDATE ON TABLE rating.formula_component TO api_write_admin;
GRANT INSERT,UPDATE ON TABLE rating.formula_definition TO api_write_admin;
GRANT SELECT ON TABLE rating.official_account_rating_observation TO api_write_admin;
GRANT INSERT ON TABLE rating.official_rating_observation TO api_write_admin;
GRANT SELECT ON TABLE rating.official_institution_rating_observation TO api_write_admin;
GRANT INSERT ON TABLE rating.population_observation TO api_write_admin;
GRANT INSERT,UPDATE ON TABLE rating.rating_component_result TO api_write_admin;
GRANT SELECT,USAGE ON SEQUENCE rating.rating_component_result_id_seq TO api_write_admin;
GRANT INSERT,UPDATE ON TABLE rating.rating_result TO api_write_admin;
GRANT INSERT,UPDATE ON TABLE rating.rating_run TO api_write_admin;

-- collector_ingest (60)
GRANT USAGE ON SCHEMA analytics TO collector_ingest;
GRANT USAGE ON SCHEMA catalog TO collector_ingest;
GRANT USAGE ON SCHEMA ingest TO collector_ingest;
GRANT USAGE ON SCHEMA ops_and_admin TO collector_ingest;
GRANT SELECT ON TABLE catalog.institution TO collector_ingest;
GRANT SELECT ON TABLE catalog.platform_account TO collector_ingest;
GRANT UPDATE(current_username) ON TABLE catalog.platform_account TO collector_ingest;
GRANT UPDATE(current_title) ON TABLE catalog.platform_account TO collector_ingest;
GRANT UPDATE(current_url) ON TABLE catalog.platform_account TO collector_ingest;
GRANT UPDATE(updated_at) ON TABLE catalog.platform_account TO collector_ingest;
GRANT UPDATE(row_version) ON TABLE catalog.platform_account TO collector_ingest;
GRANT SELECT ON TABLE catalog.visible_institution TO collector_ingest;
GRANT SELECT ON TABLE catalog.visible_platform_account TO collector_ingest;
GRANT SELECT,INSERT ON TABLE ingest.metric_evidence_dictionary TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE ingest.metric_evidence_dictionary_id_seq TO collector_ingest;
GRANT SELECT,INSERT,UPDATE ON TABLE ingest.publication TO collector_ingest;
GRANT SELECT,INSERT ON TABLE ingest.publication_metric_snapshot TO collector_ingest;
GRANT SELECT ON TABLE ingest.publication_metric_snapshot_resolved TO collector_ingest;
GRANT SELECT ON TABLE ingest.publication_metric_snapshot_active TO collector_ingest;
GRANT SELECT ON TABLE ingest.visible_publication TO collector_ingest;
GRANT ALL ON FUNCTION ops_and_admin.ensure_publication_legacy_alias(p_publication uuid) TO collector_ingest;
GRANT ALL ON FUNCTION ops_and_admin.ensure_publication_metric_partition(p_month date) TO collector_ingest;
GRANT SELECT,INSERT ON TABLE analytics.dataset_revision TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE analytics.dataset_revision_id_seq TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE analytics.institution_daily_metrics_id_seq TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE analytics.institution_metric_aggregate_id_seq TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE analytics.institution_monthly_metrics_id_seq TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE analytics.institution_period_metrics_id_seq TO collector_ingest;
GRANT SELECT,INSERT ON TABLE catalog.account_external_identity TO collector_ingest;
GRANT UPDATE(valid_to) ON TABLE catalog.account_external_identity TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE catalog.account_external_identity_id_seq TO collector_ingest;
GRANT SELECT,INSERT ON TABLE catalog.account_identity_history TO collector_ingest;
GRANT UPDATE(valid_to) ON TABLE catalog.account_identity_history TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE catalog.account_identity_history_id_seq TO collector_ingest;
GRANT SELECT,INSERT ON TABLE ingest.account_metric_snapshot TO collector_ingest;
GRANT SELECT ON TABLE ingest.account_metric_snapshot_active TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE ingest.account_metric_snapshot_id_seq TO collector_ingest;
GRANT SELECT,INSERT,UPDATE ON TABLE ingest.collection_account_result TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE ingest.collection_account_result_id_seq TO collector_ingest;
GRANT SELECT,INSERT,UPDATE ON TABLE ingest.collection_run TO collector_ingest;
GRANT SELECT,INSERT ON TABLE ingest.content_group TO collector_ingest;
GRANT SELECT,INSERT ON TABLE ingest.deletion_observation TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE ingest.deletion_observation_id_seq TO collector_ingest;
GRANT SELECT,INSERT ON TABLE ingest.evidence_quarantine TO collector_ingest;
GRANT SELECT,INSERT ON TABLE ingest.publication_availability_event TO collector_ingest;
GRANT SELECT,INSERT,UPDATE ON TABLE ingest.publication_availability_state TO collector_ingest;
GRANT SELECT,INSERT,UPDATE ON TABLE ingest.publication_identity TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE ingest.publication_identity_id_seq TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE ingest.publication_metric_snapshot_id_seq TO collector_ingest;
GRANT SELECT,INSERT ON TABLE ingest.raw_payload TO collector_ingest;
GRANT SELECT,INSERT ON TABLE ingest.reaction_breakdown TO collector_ingest;
GRANT SELECT,INSERT,UPDATE ON TABLE ops_and_admin.operational_checkpoint TO collector_ingest;
GRANT SELECT,INSERT ON TABLE ops_and_admin.outbox_event TO collector_ingest;
GRANT UPDATE(available_at) ON TABLE ops_and_admin.outbox_event TO collector_ingest;
GRANT UPDATE(published_at) ON TABLE ops_and_admin.outbox_event TO collector_ingest;
GRANT UPDATE(publish_attempts) ON TABLE ops_and_admin.outbox_event TO collector_ingest;
GRANT UPDATE(last_error_code) ON TABLE ops_and_admin.outbox_event TO collector_ingest;
GRANT SELECT,USAGE ON SEQUENCE ops_and_admin.outbox_event_id_seq TO collector_ingest;
GRANT SELECT ON TABLE ops_and_admin.schema_contract TO collector_ingest;

-- maintenance (75)
GRANT USAGE ON SCHEMA analytics TO maintenance;
GRANT USAGE ON SCHEMA catalog TO maintenance;
GRANT USAGE ON SCHEMA ingest TO maintenance;
GRANT USAGE ON SCHEMA ops_and_admin TO maintenance;
GRANT USAGE ON SCHEMA rating TO maintenance;
GRANT ALL ON FUNCTION analytics.anomaly_operational_metrics() TO maintenance;
GRANT SELECT ON TABLE catalog.institution TO maintenance;
GRANT SELECT ON TABLE catalog.platform_account TO maintenance;
GRANT SELECT ON TABLE catalog.visible_institution TO maintenance;
GRANT SELECT ON TABLE catalog.visible_platform_account TO maintenance;
GRANT SELECT ON TABLE ingest.metric_evidence_dictionary TO maintenance;
GRANT SELECT ON TABLE ingest.publication TO maintenance;
GRANT SELECT ON TABLE ingest.publication_metric_snapshot TO maintenance;
GRANT SELECT ON TABLE ingest.publication_metric_snapshot_resolved TO maintenance;
GRANT SELECT ON TABLE ingest.publication_metric_snapshot_active TO maintenance;
GRANT SELECT ON TABLE ingest.visible_publication TO maintenance;
GRANT ALL ON FUNCTION analytics.publication_snapshot_slice(p_publication uuid, p_month date) TO maintenance;
GRANT ALL ON FUNCTION ops_and_admin.abort_publication_archive(p_month date) TO maintenance;
GRANT ALL ON FUNCTION ops_and_admin.begin_publication_archive(p_month date) TO maintenance;
GRANT ALL ON FUNCTION ops_and_admin.ensure_publication_metric_partition(p_month date) TO maintenance;
GRANT ALL ON FUNCTION ops_and_admin.public_health_snapshot() TO maintenance;
GRANT ALL ON FUNCTION ops_and_admin.publication_archive_record(p_month date, p_id bigint) TO maintenance;
GRANT ALL ON FUNCTION ops_and_admin.publication_partition_digest(p_month date) TO maintenance;
GRANT ALL ON FUNCTION ops_and_admin.purge_expired_raw_payload(p_limit integer) TO maintenance;
GRANT ALL ON FUNCTION ops_and_admin.purge_raw_evidence_reference(p_uri text, p_now timestamp with time zone) TO maintenance;
GRANT ALL ON FUNCTION ops_and_admin.refresh_storage_observation() TO maintenance;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE analytics.comparison_cohort TO maintenance;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE analytics.comparison_cohort_member TO maintenance;
GRANT SELECT,INSERT ON TABLE analytics.dataset_revision TO maintenance;
GRANT SELECT,USAGE ON SEQUENCE analytics.dataset_revision_id_seq TO maintenance;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE analytics.institution_daily_metrics TO maintenance;
GRANT SELECT,USAGE ON SEQUENCE analytics.institution_daily_metrics_id_seq TO maintenance;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE analytics.institution_metric_aggregate TO maintenance;
GRANT SELECT,USAGE ON SEQUENCE analytics.institution_metric_aggregate_id_seq TO maintenance;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE analytics.institution_monthly_metrics TO maintenance;
GRANT SELECT,USAGE ON SEQUENCE analytics.institution_monthly_metrics_id_seq TO maintenance;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE analytics.institution_period_metrics TO maintenance;
GRANT SELECT,USAGE ON SEQUENCE analytics.institution_period_metrics_id_seq TO maintenance;
GRANT SELECT ON TABLE analytics.legacy_overview_account TO maintenance;
GRANT SELECT ON TABLE analytics.legacy_overview_card TO maintenance;
GRANT SELECT ON TABLE analytics.legacy_period_policy TO maintenance;
GRANT SELECT ON TABLE analytics.metric_semantic_definition TO maintenance;
GRANT SELECT ON TABLE analytics.platform_metric_capability TO maintenance;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE analytics.publication_latest TO maintenance;
GRANT SELECT ON TABLE ingest.account_metric_snapshot TO maintenance;
GRANT SELECT ON TABLE ingest.account_metric_snapshot_active TO maintenance;
GRANT SELECT ON TABLE ingest.collection_account_result TO maintenance;
GRANT SELECT ON TABLE ingest.collection_run TO maintenance;
GRANT SELECT ON TABLE ingest.evidence_quarantine TO maintenance;
GRANT SELECT ON TABLE ingest.publication_availability_event TO maintenance;
GRANT SELECT ON TABLE ingest.publication_availability_state TO maintenance;
GRANT SELECT ON TABLE ingest.publication_identity TO maintenance;
GRANT SELECT ON TABLE ingest.publication_metric_snapshot_default TO maintenance;
GRANT SELECT ON TABLE ingest.raw_payload TO maintenance;
GRANT SELECT ON TABLE ingest.reaction_breakdown TO maintenance;
GRANT SELECT ON TABLE ingest.reaction_breakdown_default TO maintenance;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE ops_and_admin.archive_manifest TO maintenance;
GRANT SELECT ON TABLE ops_and_admin.archive_object_attestation TO maintenance;
GRANT SELECT ON TABLE ops_and_admin.operational_checkpoint TO maintenance;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE ops_and_admin.outbox_event TO maintenance;
GRANT SELECT,USAGE ON SEQUENCE ops_and_admin.outbox_event_id_seq TO maintenance;
GRANT SELECT ON TABLE ops_and_admin.publication_partition_fence TO maintenance;
GRANT SELECT ON TABLE ops_and_admin.recovery_policy TO maintenance;
GRANT SELECT ON TABLE ops_and_admin.retention_policy TO maintenance;
GRANT SELECT ON TABLE ops_and_admin.schema_contract TO maintenance;
GRANT SELECT ON TABLE ops_and_admin.storage_observation TO maintenance;
GRANT SELECT ON TABLE rating.formula_component TO maintenance;
GRANT SELECT ON TABLE rating.formula_definition TO maintenance;
GRANT SELECT ON TABLE rating.official_account_rating_observation TO maintenance;
GRANT SELECT ON TABLE rating.official_import TO maintenance;
GRANT SELECT ON TABLE rating.official_institution_rating_observation TO maintenance;
GRANT SELECT ON TABLE rating.rating_component_result TO maintenance;
GRANT SELECT ON TABLE rating.rating_result TO maintenance;
GRANT SELECT ON TABLE rating.rating_run TO maintenance;

-- outbox_worker (9)
GRANT USAGE ON SCHEMA ops_and_admin TO outbox_worker;
GRANT SELECT ON TABLE ops_and_admin.outbox_event TO outbox_worker;
GRANT UPDATE(available_at) ON TABLE ops_and_admin.outbox_event TO outbox_worker;
GRANT UPDATE(published_at) ON TABLE ops_and_admin.outbox_event TO outbox_worker;
GRANT UPDATE(publish_attempts) ON TABLE ops_and_admin.outbox_event TO outbox_worker;
GRANT UPDATE(last_error_code) ON TABLE ops_and_admin.outbox_event TO outbox_worker;
GRANT UPDATE(terminal_at) ON TABLE ops_and_admin.outbox_event TO outbox_worker;
GRANT UPDATE(terminal_reason) ON TABLE ops_and_admin.outbox_event TO outbox_worker;
GRANT SELECT ON TABLE ops_and_admin.schema_contract TO outbox_worker;

-- storage_observer (2)
GRANT SELECT ON TABLE ingest.collection_run TO storage_observer;
GRANT SELECT ON TABLE ops_and_admin.outbox_event TO storage_observer;

-- служебные (REVOKE) (48)
REVOKE USAGE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.anomaly_input_is_unchanged(p_publication_id uuid, p_input_hash text, p_manifest_hash text) FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.anomaly_operational_metrics() FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.append_anomaly_review(p_finding_id uuid, p_decision text, p_private_comment text, p_subject text, p_correlation_id uuid, p_idempotency_key uuid, p_request_digest text) FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.create_manual_anomaly_signal(p_publication_id uuid, p_metric text, p_severity text, p_explanation_code text, p_start_at timestamp with time zone, p_end_at timestamp with time zone, p_evidence jsonb, p_subject text, p_correlation_id uuid, p_idempotency_key uuid, p_request_digest text) FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.extract_publication_history_as_of(p_publication_ids uuid[], p_source_dataset_revision bigint, p_max_points integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.guard_legacy_period_policy() FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.legacy_period_first_age_limit(p_revision bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.observation_quality_from_rank(p_rank integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.observation_quality_rank(p_quality ingest.observation_quality) FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.ordered_history_reactions(p_text text, p_signed boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.publication_snapshot_slice(p_publication uuid, p_month date) FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.publish_anomaly_failure(p_publication_id uuid, p_claim_token uuid, p_generation bigint, p_attempt_key uuid, p_source_revision bigint, p_manifest_hash text, p_preprocessor text, p_aggregator text, p_semantic_version integer, p_capability_version integer, p_started_at timestamp with time zone, p_error_code text, p_retry_seconds integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.publish_anomaly_success(p_publication_id uuid, p_claim_token uuid, p_generation bigint, p_attempt_key uuid, p_source_revision bigint, p_input_hash text, p_manifest_hash text, p_preprocessor text, p_aggregator text, p_semantic_version integer, p_capability_version integer, p_started_at timestamp with time zone, p_status text, p_score numeric, p_severity text, p_findings jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.refresh_history_reaction_details(p_revision bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics.refresh_official_account_ratings(p_revision bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION ingest.assert_publication_snapshot_month() FROM PUBLIC;
REVOKE ALL ON FUNCTION ingest.fence_reaction_insert() FROM PUBLIC;
REVOKE ALL ON FUNCTION ingest.prepare_immutable_account_snapshot() FROM PUBLIC;
REVOKE ALL ON FUNCTION ingest.prepare_immutable_publication_snapshot() FROM PUBLIC;
REVOKE ALL ON FUNCTION ingest.reject_evidence_dictionary_mutation() FROM PUBLIC;
REVOKE ALL ON FUNCTION ingest.reject_new_unavailable_evidence() FROM PUBLIC;
REVOKE ALL ON FUNCTION ingest.reject_observation_mutation() FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.abort_publication_archive(p_month date) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.allocate_catalog_alias(p_type text, p_target uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.assert_publication_partition_writable(p_month date) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.begin_publication_archive(p_month date) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.catalog_command(p_action text, p_target uuid, p_expected bigint, p_body jsonb, p_actor text, p_correlation uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.claim_anomaly_candidates(p_limit integer, p_lease_seconds integer, p_claim_token uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.complete_anomaly_noop(p_publication_id uuid, p_claim_token uuid, p_generation bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.drop_publication_metric_partition_v21(p_month date, p_manifest_id uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.ensure_publication_legacy_alias(p_publication uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.ensure_publication_metric_partition(p_month date) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.import_official_rating(p_payload jsonb, p_actor text, p_correlation uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.legacy_account_presentation(p_account uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.mark_anomaly_candidate() FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.pin_latest_anomaly_source_revision() FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.previous_official_rating(p_actor text, p_correlation uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.public_health_snapshot() FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.publication_archive_record(p_month date, p_id bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.publication_partition_digest(p_month date) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.purge_expired_raw_payload(p_limit integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.purge_raw_evidence_reference(p_uri text, p_now timestamp with time zone) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.record_anomaly_attempt_tombstone(p_attempt_id uuid, p_superseded_by uuid, p_reason text) FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.refresh_storage_observation() FROM PUBLIC;
REVOKE ALL ON FUNCTION ops_and_admin.seed_anomaly_backfill(p_limit integer, p_manifest_hash text) FROM PUBLIC;
REVOKE ALL ON FUNCTION rating.reject_published_component_mutation() FROM PUBLIC;
REVOKE ALL ON FUNCTION rating.reject_published_formula_mutation() FROM PUBLIC;

-- ingest.metric_evidence_dictionary (5)
-- Интернирование evidence перенесено из SECURITY DEFINER функции в код
-- коллектора, поэтому коллекторным ролям нужны прямые права на словарь.
GRANT SELECT, INSERT ON TABLE ingest.metric_evidence_dictionary TO collector_ingest;
GRANT USAGE, SELECT ON SEQUENCE ingest.metric_evidence_dictionary_id_seq TO collector_ingest;
