-- 0059 — упакованная история замеров публикаций.
--
-- Каждый замер был строкой ingest.publication_metric_snapshot: ~410 байт
-- данных и ~360 байт индексов, а разбивка реакций — ещё строками
-- ingest.reaction_breakdown. На сентябрь 2026 — 12,5 млн строк и 9,4 ГБ ради
-- 31 тыс. постов. Замеры старше двух суток больше не меняются, и строка на
-- замер им не нужна.
--
-- Горячий слой остаётся прежним: запись, триггеры, исправления, отсев
-- повторов. Упаковщик переносит замеры старше границы в одну строку на
-- публикацию — типизированные массивы со сжатием lz4 (~27 байт на замер) — и
-- удаляет их из горячих таблиц. Ничего не теряется: каждая версия каждого
-- бакета, все счётчики, качества, флаги, время сбора и записи, запуск,
-- evidence и разбивка реакций. Только в горячем слое живут технические
-- source_fingerprint, semantic_fingerprint и ingested_xid: первые два нужны
-- лишь для отсева повторов при приёме, третий — для ограждения разбивки.
--
-- Массивы элементные: точку собирает unnest … WITH ORDINALITY без оконных
-- функций, поэтому прежний SQL читает обе части через одно представление.
--   collected_at = observed_at + collected_lag мкс
--   created_at   = collected_at + created_lag мкс
--   age_seconds  = ⌊observed_at − published_at⌋ + age_residual
--   bucket       = ⌊epoch(observed_at) / 300⌋ + bucket_residual
--   codes        = качество ×5 по 3 бита, interval_uncertain (бит 15),
--                  synthetic (16), visible — последняя версия в бакете (17)
--
-- Откат: функции и представления вернуть из 0011/0012/0058, таблицу удалить
-- только после распаковки (ingest.unpack_publication_history).
BEGIN;
SET LOCAL lock_timeout = '5s';

-- Запуск сбора в массиве — четырёхбайтный номер вместо uuid.
ALTER TABLE ingest.collection_run ADD COLUMN IF NOT EXISTS seq integer GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS collection_run_seq_key ON ingest.collection_run (seq);

CREATE TABLE IF NOT EXISTS ingest.publication_metric_history (
    publication_id uuid PRIMARY KEY REFERENCES ingest.publication (id) ON DELETE CASCADE,
    published_month date NOT NULL,
    published_at timestamptz NOT NULL,
    packed_through timestamptz NOT NULL,
    -- Есть горячие строки ниже packed_through (поздний повтор или исправление):
    -- видимость упакованных точек тогда сверяется с ними.
    late_rows boolean NOT NULL DEFAULT false,
    point_count integer NOT NULL,
    first_observed_at timestamptz NOT NULL,
    last_observed_at timestamptz NOT NULL,
    snapshot_id bigint[] NOT NULL,
    observed_at timestamptz[] NOT NULL,
    collected_lag bigint[] NOT NULL,
    created_lag bigint[] NOT NULL,
    age_residual integer[] NOT NULL,
    bucket_residual bigint[] NOT NULL,
    run_seq integer[] NOT NULL,
    views_count bigint[] NOT NULL,
    reactions_count bigint[] NOT NULL,
    comments_count bigint[] NOT NULL,
    shares_count bigint[] NOT NULL,
    codes integer[] NOT NULL,
    correction_sequence bigint[] NOT NULL,
    supersedes_snapshot_id bigint[] NOT NULL,
    correction_reason text[] NOT NULL,
    semantics_version integer[] NOT NULL,
    capability_version integer[] NOT NULL,
    evidence_id integer[] NOT NULL,
    reaction_ref integer[] NOT NULL,
    reaction_dict jsonb[] NOT NULL,
    block_sha256 bytea NOT NULL,
    packed_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    CONSTRAINT publication_metric_history_shape CHECK (
        point_count = cardinality(snapshot_id) AND point_count > 0
        AND cardinality(observed_at) = point_count AND cardinality(collected_lag) = point_count
        AND cardinality(created_lag) = point_count AND cardinality(age_residual) = point_count
        AND cardinality(bucket_residual) = point_count AND cardinality(run_seq) = point_count
        AND cardinality(views_count) = point_count AND cardinality(reactions_count) = point_count
        AND cardinality(comments_count) = point_count AND cardinality(shares_count) = point_count
        AND cardinality(codes) = point_count AND cardinality(correction_sequence) = point_count
        AND cardinality(supersedes_snapshot_id) = point_count AND cardinality(correction_reason) = point_count
        AND cardinality(semantics_version) = point_count AND cardinality(capability_version) = point_count
        AND cardinality(evidence_id) = point_count AND cardinality(reaction_ref) = point_count
        AND octet_length(block_sha256) = 32
        AND published_month = date_trunc('month', published_at AT TIME ZONE 'UTC')::date)
) WITH (toast_tuple_target = 128);

ALTER TABLE ingest.publication_metric_history
    ALTER COLUMN snapshot_id SET COMPRESSION lz4, ALTER COLUMN observed_at SET COMPRESSION lz4,
    ALTER COLUMN collected_lag SET COMPRESSION lz4, ALTER COLUMN created_lag SET COMPRESSION lz4,
    ALTER COLUMN age_residual SET COMPRESSION lz4, ALTER COLUMN bucket_residual SET COMPRESSION lz4,
    ALTER COLUMN run_seq SET COMPRESSION lz4, ALTER COLUMN views_count SET COMPRESSION lz4,
    ALTER COLUMN reactions_count SET COMPRESSION lz4, ALTER COLUMN comments_count SET COMPRESSION lz4,
    ALTER COLUMN shares_count SET COMPRESSION lz4, ALTER COLUMN codes SET COMPRESSION lz4,
    ALTER COLUMN correction_sequence SET COMPRESSION lz4, ALTER COLUMN supersedes_snapshot_id SET COMPRESSION lz4,
    ALTER COLUMN correction_reason SET COMPRESSION lz4, ALTER COLUMN semantics_version SET COMPRESSION lz4,
    ALTER COLUMN capability_version SET COMPRESSION lz4, ALTER COLUMN evidence_id SET COMPRESSION lz4,
    ALTER COLUMN reaction_ref SET COMPRESSION lz4, ALTER COLUMN reaction_dict SET COMPRESSION lz4;

CREATE INDEX IF NOT EXISTS publication_metric_history_month_idx
    ON ingest.publication_metric_history (published_month);

-- Качество в коде: индекс в этом списке (порядок перечисления в 0002).
CREATE OR REPLACE FUNCTION ingest.quality_code(p ingest.observation_quality) RETURNS integer
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
    AS $$ SELECT array_position(enum_range(NULL::ingest.observation_quality), p) - 1 $$;

CREATE OR REPLACE FUNCTION ingest.quality_of(code integer, shift integer) RETURNS ingest.observation_quality
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
    AS $$ SELECT ('{unknown,rounded,estimated,exact,degraded,suspected_reset,invalid}'::ingest.observation_quality[])[((code >> shift) & 7) + 1] $$;

-- Точки упакованной строки с позиции lo по hi. Единственное место, где
-- массивы превращаются в точки: SQL-функция встраивается в запрос, поэтому
-- окно по времени разворачивает только свой отрезок.
CREATE OR REPLACE FUNCTION ingest.unpack_history(h ingest.publication_metric_history, lo integer, hi integer)
RETURNS TABLE (
    published_month date, id bigint, publication_id uuid, collection_run_id uuid, observed_at timestamptz,
    age_seconds integer, sampling_bucket bigint, views_count bigint, reactions_count bigint,
    comments_count bigint, shares_count bigint, quality ingest.observation_quality,
    interval_uncertain boolean, synthetic boolean, metric_semantics_version integer,
    capability_version integer, source_fingerprint text, created_at timestamptz, collected_at timestamptz,
    ingested_xid xid8, correction_sequence bigint, supersedes_snapshot_id bigint, correction_reason text,
    views_quality ingest.observation_quality, reactions_quality ingest.observation_quality,
    comments_quality ingest.observation_quality, shares_quality ingest.observation_quality,
    metric_evidence jsonb, semantic_fingerprint bytea, visible boolean, packed boolean, reaction_breakdown jsonb)
LANGUAGE sql STABLE PARALLEL SAFE
AS $$
SELECT h.published_month, p.snapshot_id, h.publication_id, run.id, p.observed_at,
       (floor(extract(epoch FROM p.observed_at - h.published_at)))::integer + p.age_residual,
       (floor(extract(epoch FROM p.observed_at) / 300))::bigint + p.bucket_residual,
       p.views_count, p.reactions_count, p.comments_count, p.shares_count, ingest.quality_of(p.code, 0),
       (p.code >> 15) & 1 = 1, (p.code >> 16) & 1 = 1, p.semantics_version, p.capability_version,
       NULL::text, p.observed_at + (p.collected_lag + p.created_lag) * interval '1 microsecond',
       p.observed_at + p.collected_lag * interval '1 microsecond', NULL::xid8, p.correction_sequence,
       p.supersedes_snapshot_id, p.correction_reason, ingest.quality_of(p.code, 3), ingest.quality_of(p.code, 6),
       ingest.quality_of(p.code, 9), ingest.quality_of(p.code, 12), evidence.payload, NULL::bytea,
       (p.code >> 17) & 1 = 1 AND CASE WHEN h.late_rows THEN NOT EXISTS (
           SELECT 1 FROM ingest.publication_metric_snapshot successor
            WHERE successor.published_month = h.published_month
              AND successor.publication_id = h.publication_id
              AND successor.sampling_bucket = (floor(extract(epoch FROM p.observed_at) / 300))::bigint + p.bucket_residual
              AND successor.correction_sequence > p.correction_sequence) ELSE true END,
       true,
       COALESCE(h.reaction_dict[p.reaction_ref], '{}'::jsonb)
  FROM unnest(h.snapshot_id[lo:hi], h.observed_at[lo:hi], h.collected_lag[lo:hi], h.created_lag[lo:hi],
              h.age_residual[lo:hi], h.bucket_residual[lo:hi], h.run_seq[lo:hi], h.views_count[lo:hi],
              h.reactions_count[lo:hi], h.comments_count[lo:hi], h.shares_count[lo:hi], h.codes[lo:hi],
              h.correction_sequence[lo:hi], h.supersedes_snapshot_id[lo:hi], h.correction_reason[lo:hi],
              h.semantics_version[lo:hi], h.capability_version[lo:hi], h.evidence_id[lo:hi], h.reaction_ref[lo:hi])
       AS p(snapshot_id, observed_at, collected_lag, created_lag, age_residual, bucket_residual, run_seq,
            views_count, reactions_count, comments_count, shares_count, code, correction_sequence,
            supersedes_snapshot_id, correction_reason, semantics_version, capability_version, evidence_id,
            reaction_ref)
  LEFT JOIN ingest.collection_run run ON run.seq = p.run_seq
  LEFT JOIN ingest.metric_evidence_dictionary evidence ON evidence.id = p.evidence_id
$$;

-- Все точки: горячие строки и упакованные массивы, колонки
-- publication_metric_snapshot_resolved + visible, packed, reaction_breakdown.
CREATE OR REPLACE VIEW ingest.publication_metric_point AS
SELECT s.published_month, s.id, s.publication_id, s.collection_run_id, s.observed_at, s.age_seconds,
       s.sampling_bucket, s.views_count, s.reactions_count, s.comments_count, s.shares_count, s.quality,
       s.interval_uncertain, s.synthetic, s.metric_semantics_version, s.capability_version,
       s.source_fingerprint, s.created_at, s.collected_at, s.ingested_xid, s.correction_sequence,
       s.supersedes_snapshot_id, s.correction_reason, s.views_quality, s.reactions_quality,
       s.comments_quality, s.shares_quality, COALESCE(s.metric_evidence, evidence.payload) AS metric_evidence,
       s.semantic_fingerprint,
       NOT EXISTS (SELECT 1 FROM ingest.publication_metric_snapshot successor
                    WHERE successor.published_month = s.published_month
                      AND successor.publication_id = s.publication_id
                      AND successor.sampling_bucket = s.sampling_bucket
                      AND successor.correction_sequence > s.correction_sequence) AS visible,
       false AS packed,
       -- Разбивка без строк — пустой объект, как и прежде отдавала история.
       COALESCE((SELECT jsonb_object_agg(r.reaction_key, r.reaction_count ORDER BY r.reaction_key)
                   FROM ingest.reaction_breakdown r
                  WHERE r.snapshot_published_month = s.published_month AND r.snapshot_id = s.id),
                '{}'::jsonb) AS reaction_breakdown
  FROM ingest.publication_metric_snapshot s
  LEFT JOIN ingest.metric_evidence_dictionary evidence ON evidence.id = s.metric_evidence_id
UNION ALL
SELECT p.* FROM ingest.publication_metric_history h CROSS JOIN LATERAL ingest.unpack_history(h, 1, h.point_count) p;

-- Точки постов в окне [from, to): горячие — по индексу, упакованные —
-- только отрезок массивов внутри окна, посты вне окна не разворачиваются.
CREATE OR REPLACE FUNCTION ingest.publication_points_between(p_ids uuid[], p_from timestamptz, p_to timestamptz)
RETURNS SETOF ingest.publication_metric_point
LANGUAGE sql STABLE PARALLEL SAFE
AS $$
SELECT p.* FROM ingest.publication_metric_point p
 WHERE NOT p.packed AND p.publication_id = ANY (p_ids) AND p.observed_at >= p_from AND p.observed_at < p_to
UNION ALL
SELECT p.*
  FROM ingest.publication_metric_history h
 CROSS JOIN LATERAL (SELECT min(u.o)::integer AS lo, max(u.o)::integer AS hi
                       FROM unnest(h.observed_at) WITH ORDINALITY AS u(t, o)
                      WHERE u.t >= p_from AND u.t < p_to) slice
 CROSS JOIN LATERAL ingest.unpack_history(h, slice.lo, slice.hi) p
 WHERE h.publication_id = ANY (p_ids) AND h.last_observed_at >= p_from AND h.first_observed_at < p_to
   AND slice.lo IS NOT NULL
$$;

-- Одна точка по номеру снимка: горячая — по ключу, упакованная — поиском
-- номера в массиве и декодированием одного элемента.
CREATE OR REPLACE FUNCTION ingest.publication_point_by_id(p_publication_id uuid, p_published_month date, p_id bigint)
RETURNS SETOF ingest.publication_metric_point
LANGUAGE sql STABLE PARALLEL SAFE
AS $$
SELECT p.* FROM ingest.publication_metric_point p
 WHERE NOT p.packed AND p.published_month = p_published_month AND p.id = p_id
   AND p.publication_id = p_publication_id
UNION ALL
SELECT p.*
  FROM ingest.publication_metric_history h
 CROSS JOIN LATERAL (SELECT array_position(h.snapshot_id, p_id) AS i) found
 CROSS JOIN LATERAL ingest.unpack_history(h, found.i, found.i) p
 WHERE h.publication_id = p_publication_id AND found.i IS NOT NULL
$$;

-- Последняя видимая точка каждого поста не позже момента at (значение «на
-- момент» для сводок). Горячая часть — по индексу (publication_id,
-- observed_at), упакованная — отрезок до at с конца.
CREATE OR REPLACE FUNCTION ingest.publication_point_at(p_ids uuid[], p_at timestamptz)
RETURNS SETOF ingest.publication_metric_point
LANGUAGE sql STABLE PARALLEL SAFE
AS $$
SELECT DISTINCT ON (candidate.publication_id) candidate.*
  FROM (
    SELECT hot.* FROM unnest(p_ids) AS ids(publication_id)
     CROSS JOIN LATERAL (
        SELECT p.* FROM ingest.publication_metric_point p
         WHERE NOT p.packed AND p.publication_id = ids.publication_id AND p.observed_at <= p_at AND p.visible
         ORDER BY p.observed_at DESC, p.id DESC LIMIT 1) hot
    UNION ALL
    -- Обычный случай: последняя точка с битом visible находится по двум
    -- массивам, декодируется одна точка.
    SELECT packed.*
      FROM ingest.publication_metric_history h
     CROSS JOIN LATERAL (SELECT max(u.o)::integer AS i
                           FROM unnest(h.observed_at, h.codes) WITH ORDINALITY AS u(t, c, o)
                          WHERE u.t <= p_at AND (u.c >> 17) & 1 = 1) pick
     CROSS JOIN LATERAL ingest.unpack_history(h, pick.i, pick.i) packed
     WHERE h.publication_id = ANY (p_ids) AND h.first_observed_at <= p_at AND pick.i IS NOT NULL
       AND NOT h.late_rows
    UNION ALL
    -- Есть поздние горячие строки: видимость сверяется с ними, отрезок целиком.
    SELECT packed.*
      FROM ingest.publication_metric_history h
     CROSS JOIN LATERAL (SELECT max(u.o)::integer AS hi FROM unnest(h.observed_at) WITH ORDINALITY AS u(t, o)
                          WHERE u.t <= p_at) slice
     CROSS JOIN LATERAL (
        SELECT p.* FROM ingest.unpack_history(h, 1, slice.hi) p
         WHERE p.visible ORDER BY p.observed_at DESC, p.id DESC LIMIT 1) packed
     WHERE h.publication_id = ANY (p_ids) AND h.first_observed_at <= p_at AND slice.hi IS NOT NULL
       AND h.late_rows
  ) candidate
 ORDER BY candidate.publication_id, candidate.observed_at DESC, candidate.id DESC
$$;

-- Прежние представления — поверх обеих частей, колонки те же.
CREATE OR REPLACE VIEW ingest.publication_metric_snapshot_resolved AS
SELECT published_month, id, publication_id, collection_run_id, observed_at, age_seconds, sampling_bucket,
       views_count, reactions_count, comments_count, shares_count, quality, interval_uncertain, synthetic,
       metric_semantics_version, capability_version, source_fingerprint, created_at, collected_at,
       ingested_xid, correction_sequence, supersedes_snapshot_id, correction_reason, views_quality,
       reactions_quality, comments_quality, shares_quality, metric_evidence, semantic_fingerprint
  FROM ingest.publication_metric_point;

CREATE OR REPLACE VIEW ingest.publication_metric_snapshot_active AS
SELECT published_month, id, publication_id, collection_run_id, observed_at, age_seconds, sampling_bucket,
       views_count, reactions_count, comments_count, shares_count, quality, interval_uncertain, synthetic,
       metric_semantics_version, capability_version, source_fingerprint, created_at, collected_at,
       ingested_xid, correction_sequence, supersedes_snapshot_id, correction_reason, views_quality,
       reactions_quality, comments_quality, shares_quality, metric_evidence, semantic_fingerprint
  FROM ingest.publication_metric_point
 WHERE visible;

-- Упаковка. Сливает упакованное и горячие строки ниже границы, пересчитывает
-- видимость, пишет строку и удаляет перенесённые строки. Бакет переносится,
-- только когда все его версии ниже границы: иначе исправление на границе
-- разошлось бы по слоям.
CREATE OR REPLACE FUNCTION ingest.compact_publication_history(p_publication_id uuid, p_boundary timestamptz)
RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'pg_catalog', 'ingest'
SET "TimeZone" TO 'UTC'
AS $$
DECLARE
    publication_row ingest.publication%ROWTYPE;
    old_row ingest.publication_metric_history%ROWTYPE;
    moved bigint[];
    moved_months date[];
    result_row ingest.publication_metric_history%ROWTYPE;
BEGIN
    PERFORM pg_advisory_xact_lock(hashtextextended('metric-history:' || p_publication_id::text, 0));
    SELECT * INTO publication_row FROM ingest.publication WHERE id = p_publication_id;
    IF NOT FOUND THEN RETURN 0; END IF;
    SELECT * INTO old_row FROM ingest.publication_metric_history WHERE publication_id = p_publication_id FOR UPDATE;

    -- Перенос: горячие строки поста ниже границы, бакеты целиком.
    SELECT array_agg(s.id), array_agg(DISTINCT s.published_month)
      INTO moved, moved_months
      FROM ingest.publication_metric_snapshot s
     WHERE s.publication_id = p_publication_id
       AND s.observed_at < p_boundary
       AND NOT EXISTS (SELECT 1 FROM ingest.publication_metric_snapshot later
                        WHERE later.published_month = s.published_month
                          AND later.publication_id = s.publication_id
                          AND later.sampling_bucket = s.sampling_bucket
                          AND later.observed_at >= p_boundary);
    IF moved IS NULL THEN
        IF old_row.publication_id IS NOT NULL AND old_row.late_rows THEN
            UPDATE ingest.publication_metric_history SET late_rows = false WHERE publication_id = p_publication_id;
        END IF;
        RETURN 0;
    END IF;

    -- evidence из горячих строк — в словарь (запись в словарь неизменяемая).
    INSERT INTO ingest.metric_evidence_dictionary (payload, payload_sha256)
    SELECT DISTINCT s.metric_evidence, sha256(convert_to(s.metric_evidence::text, 'UTF8'))
      FROM ingest.publication_metric_snapshot s
     WHERE s.publication_id = p_publication_id AND s.id = ANY (moved)
       AND s.metric_evidence IS NOT NULL AND s.metric_evidence_id IS NULL
    ON CONFLICT (payload_sha256) DO NOTHING;

    WITH points AS (
        SELECT p.snapshot_id AS id, p.observed_at, p.collected_lag, p.created_lag, p.age_residual,
               p.bucket_residual, p.run_seq, p.views_count, p.reactions_count, p.comments_count, p.shares_count,
               p.code & (~(1 << 17)) AS code, p.correction_sequence, p.supersedes_snapshot_id, p.correction_reason,
               p.semantics_version, p.capability_version, p.evidence_id,
               old_row.reaction_dict[p.reaction_ref] AS breakdown,
               (floor(extract(epoch FROM p.observed_at) / 300))::bigint + p.bucket_residual AS bucket
          FROM unnest(old_row.snapshot_id, old_row.observed_at, old_row.collected_lag, old_row.created_lag,
                      old_row.age_residual, old_row.bucket_residual, old_row.run_seq, old_row.views_count,
                      old_row.reactions_count, old_row.comments_count, old_row.shares_count, old_row.codes,
                      old_row.correction_sequence, old_row.supersedes_snapshot_id, old_row.correction_reason,
                      old_row.semantics_version, old_row.capability_version, old_row.evidence_id,
                      old_row.reaction_ref)
               AS p(snapshot_id, observed_at, collected_lag, created_lag, age_residual, bucket_residual, run_seq,
                    views_count, reactions_count, comments_count, shares_count, code, correction_sequence,
                    supersedes_snapshot_id, correction_reason, semantics_version, capability_version,
                    evidence_id, reaction_ref)
         WHERE old_row.publication_id IS NOT NULL
        UNION ALL
        SELECT s.id, s.observed_at,
               (extract(epoch FROM s.collected_at - s.observed_at) * 1000000)::bigint,
               (extract(epoch FROM s.created_at - s.collected_at) * 1000000)::bigint,
               s.age_seconds - (floor(extract(epoch FROM s.observed_at - publication_row.published_at)))::integer,
               s.sampling_bucket - (floor(extract(epoch FROM s.observed_at) / 300))::bigint,
               run.seq, s.views_count, s.reactions_count, s.comments_count, s.shares_count,
               -- Операторы | и << в PostgreSQL одного приоритета: скобки обязательны.
               ingest.quality_code(s.quality) | (ingest.quality_code(s.views_quality) << 3)
                 | (ingest.quality_code(s.reactions_quality) << 6) | (ingest.quality_code(s.comments_quality) << 9)
                 | (ingest.quality_code(s.shares_quality) << 12)
                 | CASE WHEN s.interval_uncertain THEN 1 << 15 ELSE 0 END
                 | CASE WHEN s.synthetic THEN 1 << 16 ELSE 0 END,
               s.correction_sequence, s.supersedes_snapshot_id, s.correction_reason,
               s.metric_semantics_version, s.capability_version,
               COALESCE(s.metric_evidence_id, interned.id),
               (SELECT jsonb_object_agg(r.reaction_key, r.reaction_count ORDER BY r.reaction_key)
                  FROM ingest.reaction_breakdown r
                 WHERE r.snapshot_published_month = s.published_month AND r.snapshot_id = s.id),
               s.sampling_bucket
          FROM ingest.publication_metric_snapshot s
          JOIN ingest.collection_run run ON run.id = s.collection_run_id
          LEFT JOIN ingest.metric_evidence_dictionary interned
                 ON s.metric_evidence IS NOT NULL AND s.metric_evidence_id IS NULL
                AND interned.payload_sha256 = sha256(convert_to(s.metric_evidence::text, 'UTF8'))
         WHERE s.publication_id = p_publication_id AND s.id = ANY (moved)
    ), ranked AS (
        SELECT points.*,
               row_number() OVER (PARTITION BY bucket ORDER BY correction_sequence DESC, id DESC) = 1 AS visible,
               row_number() OVER (ORDER BY observed_at, id) AS position
          FROM points
    ), dict AS (
        SELECT breakdown, row_number() OVER (ORDER BY min(position)) AS ref
          FROM ranked WHERE breakdown IS NOT NULL GROUP BY breakdown
    )
    SELECT p_publication_id, date_trunc('month', publication_row.published_at AT TIME ZONE 'UTC')::date,
           publication_row.published_at, greatest(old_row.packed_through, p_boundary), false,
           count(*), min(r.observed_at), max(r.observed_at),
           array_agg(r.id ORDER BY r.position), array_agg(r.observed_at ORDER BY r.position),
           array_agg(r.collected_lag ORDER BY r.position), array_agg(r.created_lag ORDER BY r.position),
           array_agg(r.age_residual ORDER BY r.position), array_agg(r.bucket_residual ORDER BY r.position),
           array_agg(r.run_seq ORDER BY r.position), array_agg(r.views_count ORDER BY r.position),
           array_agg(r.reactions_count ORDER BY r.position), array_agg(r.comments_count ORDER BY r.position),
           array_agg(r.shares_count ORDER BY r.position),
           array_agg(r.code | CASE WHEN r.visible THEN 1 << 17 ELSE 0 END ORDER BY r.position),
           array_agg(r.correction_sequence ORDER BY r.position),
           array_agg(r.supersedes_snapshot_id ORDER BY r.position),
           array_agg(r.correction_reason ORDER BY r.position),
           array_agg(r.semantics_version ORDER BY r.position), array_agg(r.capability_version ORDER BY r.position),
           array_agg(r.evidence_id ORDER BY r.position), array_agg(d.ref::integer ORDER BY r.position),
           coalesce((SELECT array_agg(dict.breakdown ORDER BY dict.ref) FROM dict), '{}'::jsonb[]),
           '\x0000000000000000000000000000000000000000000000000000000000000000'::bytea,
           transaction_timestamp()
      INTO result_row
      FROM ranked r LEFT JOIN dict d ON d.breakdown = r.breakdown;

    IF EXISTS (SELECT 1 FROM unnest(result_row.run_seq) seq WHERE seq IS NULL) THEN
        RAISE EXCEPTION 'collection run without seq for publication %', p_publication_id;
    END IF;
    result_row.block_sha256 := sha256(convert_to(row(result_row.snapshot_id, result_row.observed_at,
        result_row.collected_lag, result_row.created_lag, result_row.age_residual, result_row.bucket_residual,
        result_row.run_seq, result_row.views_count, result_row.reactions_count, result_row.comments_count,
        result_row.shares_count, result_row.codes, result_row.correction_sequence,
        result_row.supersedes_snapshot_id, result_row.correction_reason, result_row.semantics_version,
        result_row.capability_version, result_row.evidence_id, result_row.reaction_ref,
        result_row.reaction_dict)::text, 'UTF8'));

    INSERT INTO ingest.publication_metric_history VALUES (result_row.*)
    ON CONFLICT (publication_id) DO UPDATE SET
        packed_through = EXCLUDED.packed_through, late_rows = false, point_count = EXCLUDED.point_count,
        first_observed_at = EXCLUDED.first_observed_at, last_observed_at = EXCLUDED.last_observed_at,
        snapshot_id = EXCLUDED.snapshot_id, observed_at = EXCLUDED.observed_at,
        collected_lag = EXCLUDED.collected_lag, created_lag = EXCLUDED.created_lag,
        age_residual = EXCLUDED.age_residual, bucket_residual = EXCLUDED.bucket_residual,
        run_seq = EXCLUDED.run_seq, views_count = EXCLUDED.views_count,
        reactions_count = EXCLUDED.reactions_count, comments_count = EXCLUDED.comments_count,
        shares_count = EXCLUDED.shares_count, codes = EXCLUDED.codes,
        correction_sequence = EXCLUDED.correction_sequence,
        supersedes_snapshot_id = EXCLUDED.supersedes_snapshot_id,
        correction_reason = EXCLUDED.correction_reason, semantics_version = EXCLUDED.semantics_version,
        capability_version = EXCLUDED.capability_version, evidence_id = EXCLUDED.evidence_id,
        reaction_ref = EXCLUDED.reaction_ref, reaction_dict = EXCLUDED.reaction_dict,
        block_sha256 = EXCLUDED.block_sha256, packed_at = EXCLUDED.packed_at;

    -- Удаление перенесённого: только под флагом упаковщика (см. reject_observation_mutation).
    PERFORM set_config('ingest.compaction', 'on', true);
    DELETE FROM ingest.reaction_breakdown r
     WHERE r.snapshot_published_month = ANY (moved_months) AND r.snapshot_id = ANY (moved);
    DELETE FROM ingest.publication_metric_snapshot s
     WHERE s.published_month = ANY (moved_months) AND s.publication_id = p_publication_id AND s.id = ANY (moved);
    PERFORM set_config('ingest.compaction', 'off', true);
    RETURN cardinality(moved);
END $$;

-- Неизменяемость: упаковщик удаляет перенесённое, больше никто.
CREATE OR REPLACE FUNCTION ingest.reject_observation_mutation() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
 -- Флаг сеанса может поставить кто угодно, поэтому проверяется и роль:
 -- удаляет только владелец таблицы снимков — им исполняется упаковщик.
 IF TG_OP='DELETE' AND current_setting('ingest.compaction', true)='on'
    AND current_user=(SELECT pg_get_userbyid(relowner) FROM pg_class
                       WHERE oid='ingest.publication_metric_snapshot'::regclass)
    AND TG_TABLE_SCHEMA='ingest'
    AND (TG_TABLE_NAME LIKE 'publication_metric_snapshot%' OR TG_TABLE_NAME LIKE 'reaction_breakdown%') THEN
   RETURN OLD;
 END IF;
 -- Only the owner-operated backfill may replace storage; logical data remains
 -- exactly identical, including every counter, timestamp and lineage field.
 IF TG_OP='UPDATE' AND current_user='migration_owner'
    AND TG_TABLE_SCHEMA='ingest' AND TG_TABLE_NAME LIKE 'publication_metric_snapshot%' THEN
   IF (to_jsonb(OLD)-ARRAY['metric_evidence','metric_evidence_id'])
        IS NOT DISTINCT FROM (to_jsonb(NEW)-ARRAY['metric_evidence','metric_evidence_id'])
      AND OLD.metric_evidence IS NOT NULL AND OLD.metric_evidence_id IS NULL
      AND NEW.metric_evidence IS NULL AND NEW.metric_evidence_id IS NOT NULL
      AND OLD.metric_evidence IS NOT DISTINCT FROM
          (SELECT payload FROM ingest.metric_evidence_dictionary WHERE id=NEW.metric_evidence_id) THEN
     RETURN NEW;
   END IF;
 END IF;
 RAISE EXCEPTION 'observations are append-only; insert a correction' USING ERRCODE='55000';
END $$;

-- Вставка: поздний замер старше суток сверяется и с упакованным бакетом.
-- Точный повтор упакованной точки отбрасывается, иное становится
-- исправлением поверх всех версий бакета в обоих слоях.
CREATE OR REPLACE FUNCTION ingest.prepare_immutable_publication_snapshot() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'ingest', 'ops_and_admin'
    AS $$
DECLARE previous ingest.publication_metric_snapshot%ROWTYPE;
 packed record; packed_sequence bigint; packed_id bigint; hot_sequence bigint;
BEGIN
 NEW.ingested_xid:=pg_current_xact_id();
 PERFORM ops_and_admin.assert_publication_partition_writable(NEW.published_month);
 PERFORM pg_advisory_xact_lock(hashtextextended('observation:'||NEW.published_month::text||':'||NEW.publication_id::text||':'||NEW.sampling_bucket::text,0));
 NEW.views_quality:=coalesce(NEW.views_quality,NEW.quality);
 NEW.reactions_quality:=coalesce(NEW.reactions_quality,NEW.quality);
 NEW.comments_quality:=coalesce(NEW.comments_quality,NEW.quality);
 NEW.shares_quality:=coalesce(NEW.shares_quality,NEW.quality);
 SELECT * INTO previous FROM ingest.publication_metric_snapshot
  WHERE published_month=NEW.published_month AND publication_id=NEW.publication_id
   AND sampling_bucket=NEW.sampling_bucket AND source_fingerprint=NEW.source_fingerprint;
 IF FOUND THEN
   previous.metric_evidence:=coalesce(previous.metric_evidence,(SELECT payload FROM ingest.metric_evidence_dictionary WHERE id=previous.metric_evidence_id));
   IF (to_jsonb(previous)-ARRAY['id','created_at','collection_run_id','correction_sequence','supersedes_snapshot_id','correction_reason','ingested_xid','metric_evidence_id'])
    IS DISTINCT FROM (to_jsonb(NEW)-ARRAY['id','created_at','collection_run_id','correction_sequence','supersedes_snapshot_id','correction_reason','ingested_xid','metric_evidence_id']) THEN
     RAISE EXCEPTION 'fingerprint reused for different observation' USING ERRCODE='23505';
   END IF;
   RETURN NULL;
 END IF;
 IF NEW.observed_at < transaction_timestamp() - interval '1 day'
    AND EXISTS (SELECT 1 FROM ingest.publication_metric_history WHERE publication_id=NEW.publication_id) THEN
   PERFORM pg_advisory_xact_lock(hashtextextended('metric-history:'||NEW.publication_id::text,0));
   SELECT bool_or(p.observed_at=NEW.observed_at AND p.views_count IS NOT DISTINCT FROM NEW.views_count
                  AND p.reactions_count IS NOT DISTINCT FROM NEW.reactions_count
                  AND p.comments_count IS NOT DISTINCT FROM NEW.comments_count
                  AND p.shares_count IS NOT DISTINCT FROM NEW.shares_count
                  AND p.quality=NEW.quality AND p.views_quality=NEW.views_quality
                  AND p.reactions_quality=NEW.reactions_quality AND p.comments_quality=NEW.comments_quality
                  AND p.shares_quality=NEW.shares_quality AND p.synthetic=NEW.synthetic
                  AND p.interval_uncertain=NEW.interval_uncertain) AS replay,
          max(p.correction_sequence) AS top
     INTO packed
     FROM ingest.publication_metric_point p
    WHERE p.packed AND p.publication_id=NEW.publication_id AND p.published_month=NEW.published_month
      AND p.sampling_bucket=NEW.sampling_bucket;
   IF packed.replay THEN RETURN NULL; END IF;
   IF packed.top IS NOT NULL THEN
     SELECT p.id INTO packed_id FROM ingest.publication_metric_point p
      WHERE p.packed AND p.publication_id=NEW.publication_id AND p.published_month=NEW.published_month
        AND p.sampling_bucket=NEW.sampling_bucket AND p.correction_sequence=packed.top;
     packed_sequence:=packed.top;
     UPDATE ingest.publication_metric_history SET late_rows=true WHERE publication_id=NEW.publication_id;
   END IF;
 END IF;
 SELECT * INTO previous FROM ingest.publication_metric_snapshot
  WHERE published_month=NEW.published_month AND publication_id=NEW.publication_id
   AND sampling_bucket=NEW.sampling_bucket ORDER BY correction_sequence DESC LIMIT 1;
 hot_sequence:=CASE WHEN FOUND THEN previous.correction_sequence END;
 IF packed_sequence IS NOT NULL AND (hot_sequence IS NULL OR packed_sequence>hot_sequence) THEN
   NEW.correction_sequence:=packed_sequence+1;
   NEW.supersedes_snapshot_id:=packed_id;
 ELSE
   NEW.correction_sequence:=CASE WHEN hot_sequence IS NOT NULL THEN hot_sequence+1 ELSE 0 END;
   NEW.supersedes_snapshot_id:=previous.id;
 END IF;
 NEW.correction_reason:=CASE WHEN NEW.supersedes_snapshot_id IS NOT NULL THEN coalesce(nullif(btrim(NEW.correction_reason),''),'provider_payload_changed') END;
 RETURN NEW;
END $$;

-- Посты, которым есть что упаковать: строки старше границы.
CREATE OR REPLACE FUNCTION ingest.compactable_publications(p_boundary timestamptz, p_limit integer)
RETURNS TABLE (publication_id uuid)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path TO 'pg_catalog', 'ingest'
AS $$
    -- Полусоединение по индексу (publication_id, observed_at): LIMIT
    -- останавливает поиск, не перебирая все горячие строки.
    SELECT p.id
      FROM ingest.publication p
     WHERE EXISTS (SELECT 1 FROM ingest.publication_metric_snapshot s
                    WHERE s.publication_id = p.id AND s.observed_at < p_boundary)
     LIMIT p_limit
$$;

REVOKE ALL ON FUNCTION ingest.compact_publication_history(uuid, timestamptz) FROM PUBLIC;
REVOKE ALL ON FUNCTION ingest.compactable_publications(timestamptz, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ingest.compact_publication_history(uuid, timestamptz) TO maintenance;
GRANT EXECUTE ON FUNCTION ingest.compactable_publications(timestamptz, integer) TO maintenance;

-- Читают то же, что читали таблицу снимков.
GRANT SELECT ON ingest.publication_metric_history TO maintenance, api_read, analytics_worker, collector_ingest;
GRANT SELECT ON ingest.publication_metric_point TO maintenance, api_read, analytics_worker, collector_ingest;
GRANT EXECUTE ON FUNCTION ingest.unpack_history(ingest.publication_metric_history, integer, integer),
    ingest.publication_points_between(uuid[], timestamptz, timestamptz),
    ingest.publication_point_at(uuid[], timestamptz),
    ingest.publication_point_by_id(uuid, date, bigint)
    TO maintenance, api_read, analytics_worker, collector_ingest;
GRANT SELECT ON ingest.collection_run TO api_read, analytics_worker;

COMMIT;
