import { accountHref, publicationHref } from "@/lib/entity-routes";
import Link from "@/components/native-link";
import { legacyDate, legacyNumber, PLATFORM_LABELS, PLATFORM_LONG_LABELS, publicationLabel } from "@/lib/format";
import type { AccountView, InstitutionView, PublicationListItem } from "@/lib/types";
export function InstitutionDetail({institution,accounts,posts,accountsTruncated=false}:{institution:InstitutionView;accounts:AccountView[];posts:(PublicationListItem & {account:AccountView})[];accountsTruncated?:boolean}) {
  const telegram=institution.platform === "telegram";
  return <><span data-active-platform={institution.platform} hidden /><p><Link href={`/?platform=${institution.platform}`} prefetch={false}>← К обзору</Link></p><h1>{institution.shortName || institution.canonicalName}</h1><p className="lead">{institution.canonicalName}{institution.platform !== "all" ? ` · ${PLATFORM_LONG_LABELS[institution.platform]}` : ""}</p>
  {accountsTruncated ? <p className="panel-note">Показаны первые 100 аккаунтов учреждения.</p> : null}<section className="grid institution-accounts">{accounts.map((account) => <article className="card platform-overview-card" key={account.accountId}><span className={`platform-chip platform-${account.platform}`}>{PLATFORM_LABELS[account.platform]}</span><h2 className="mt">{account.title || account.username || account.canonicalExternalId}</h2><div className="muted">{telegram && account.username ? `@${account.username} · ` : ""}{legacyNumber(account.stats?.subscriberCount ?? null)} подписчиков</div><div className="overview-footer"><div className={account.stats?.lastError ? "bad" : account.stats?.lastCheckedAt ? "ok" : "muted"}>{account.stats?.lastError || (account.stats?.lastCheckedAt ? "Источник опрашивается" : "Ожидает первого опроса")}</div><p><Link href={accountHref(account.accountId)} prefetch={false}>Открыть публикации</Link>{account.url?.startsWith("https://") ? <> · <a className="external" href={account.url} target="_blank" rel="noopener noreferrer">Официальный аккаунт</a></> : null}</p></div></article>)}{!accounts.length ? <div className="panel">{telegram ? "Telegram-каналы вуза не добавлены." : "Для выбранной площадки официальный аккаунт не добавлен."}</div> : null}</section>
  <section className="panel section institution-publications"><div className="section-head"><h2>Последние публикации</h2><span className="period-badge">{posts.length}</span></div>{posts.length ? <div className="table-wrap"><table><thead><tr><th>{telegram ? "Канал" : "Площадка"}</th><th>Опубликовано</th><th>Публикация</th><th>{telegram ? "Реакции" : "Просмотры"}</th><th>{telegram ? "Просмотры" : "Реакции"}</th><th>Комментарии</th>{!telegram ? <th>Репосты</th> : null}</tr></thead><tbody>{posts.map((post) => <tr key={post.publicationId}><td>{telegram ? <Link href={accountHref(post.account.accountId)} prefetch={false}>{post.account.title || `@${post.account.username}`}</Link> : <span className={`platform-chip platform-${post.account.platform}`}>{post.account.platform.toUpperCase()}</span>}</td><td>{legacyDate(post.publishedAt,true)}</td><td>{post.publicationId ? <Link href={publicationHref(post.publicationId)} prefetch={false}>{publicationLabel(post.displayExternalId ?? post.externalId,post.account.platform)}</Link> : publicationLabel(post.displayExternalId ?? post.externalId,post.account.platform)}{!telegram && post.publicUrl?.startsWith("https://") ? <> · <a className="external" href={post.publicUrl} target="_blank" rel="noopener noreferrer">оригинал</a></> : null}{post.deletedAt ? <> · <span className="pill deleted">удалена</span></> : null}{post.repost ? <> · <span className="pill repost">репост</span></> : null}{post.joint ? <> · <span className="pill coauthor">+{post.additionalAuthorCount} авт.</span></> : null}</td><td>{legacyNumber(telegram ? post.reactions.value : post.views.value)}</td><td>{legacyNumber(telegram ? post.views.value : post.reactions.value)}</td><td>{legacyNumber(post.comments.value)}</td>{!telegram ? <td>{legacyNumber(post.shares.value)}</td> : null}</tr>)}</tbody></table></div> : <div className="empty-state">Откройте нужный аккаунт выше, чтобы посмотреть его публикации.</div>}</section></>;
}
