bind 127.0.0.1 ::1
protected-mode yes
port 6379
tcp-backlog 128
timeout 0
tcp-keepalive 60
databases 1
save ""
appendonly no
dir /run/m-ranked-redis
logfile ""
maxclients 256
maxmemory 256mb
maxmemory-policy allkeys-lru
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
rename-command FLUSHALL ""
rename-command FLUSHDB ""
