import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";
import { parse } from "yaml";

const source = new URL("../../contracts/openapi/m-ranked-v1.yaml", import.meta.url);
const output = new URL("../../contracts/openapi/m-ranked-v1-client.ts", import.meta.url);
const reference = new URL("../lib/api-reference.generated.json", import.meta.url);
const content = await readFile(source, "utf8");
const hash = createHash("sha256").update(content).digest("hex");
const generated = `// Generated by frontend/scripts/generate-openapi.mjs. Do not edit.\n// Source-SHA256: ${hash}\n\n${astToString(await openapiTS(source))}`;

// Справочник открытого API для /methodology/api: только публичные чтения.
// Служебные (здоровье, эмодзи, карта сайта) и административные методы в него
// не входят.
const HIDDEN = [/^\/api\/v1\/admin\//, /^\/api\/v1\/health\//, /^\/api\/v1\/emoji\//, /^\/api\/v1\/sitemap/];
const spec = parse(content);
const resolve = (node) => {
  let value = node;
  while (value && typeof value === "object" && "$ref" in value) {
    value = value.$ref.replace(/^#\//, "").split("/").reduce((target, key) => target[key], spec);
  }
  return value;
};
const typeOf = (schema) => {
  const value = resolve(schema) ?? {};
  if (value.oneOf || value.anyOf) return [...new Set((value.oneOf ?? value.anyOf).map(typeOf))].join(" | ");
  if (Array.isArray(value.type)) return value.type.filter((item) => item !== "null").join(" | ") + (value.type.includes("null") ? " | null" : "");
  if (value.type === "array") return `${typeOf(value.items)}[]`;
  if (value.format === "uuid") return "uuid";
  if (value.format === "date-time") return "date-time";
  return value.type ?? "object";
};
const operations = [];
for (const [path, item] of Object.entries(spec.paths)) {
  const operation = item.get;
  if (!operation || HIDDEN.some((pattern) => pattern.test(path))) continue;
  const parameters = (operation.parameters ?? []).map(resolve)
    .filter((parameter) => parameter.in !== "header")
    .map((parameter) => {
      const schema = resolve(parameter.schema) ?? {};
      return {
        name: parameter.name, in: parameter.in, required: Boolean(parameter.required), type: typeOf(parameter.schema),
        ...(schema.enum ? { enum: schema.enum } : {}),
        ...(schema.default !== undefined ? { default: schema.default } : {}),
        ...(schema.minimum !== undefined ? { minimum: schema.minimum } : {}),
        ...(schema.maximum !== undefined ? { maximum: schema.maximum } : {}),
      };
    });
  const ok = resolve(operation.responses?.["200"]);
  const schemaRef = ok?.content?.["application/json"]?.schema?.$ref;
  const schema = resolve(ok?.content?.["application/json"]?.schema) ?? {};
  operations.push({
    operationId: operation.operationId, path, summary: operation.summary ?? "",
    parameters,
    response: schemaRef ? schemaRef.split("/").at(-1) : null,
    fields: Object.entries(schema.properties ?? {}).map(([name, property]) => ({ name, type: typeOf(property) })),
  });
}
const digest = `${JSON.stringify({ sourceSha256: hash, version: spec.info.version, operations }, null, 2)}\n`;

if (process.argv.includes("--check")) {
  if (generated !== await readFile(output, "utf8") || digest !== await readFile(reference, "utf8").catch(() => "")) {
    console.error("OpenAPI client drift: run pnpm generate:api and commit the generated contract.");
    process.exitCode = 1;
  }
} else {
  await writeFile(output, generated);
  await writeFile(reference, digest);
}
