import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";

const source = new URL("../../contracts/openapi/m-ranked-v1.yaml", import.meta.url);
const output = new URL("../../contracts/openapi/m-ranked-v1-client.ts", import.meta.url);
const content = await readFile(source, "utf8");
const hash = createHash("sha256").update(content).digest("hex");
const generated = `// Generated by frontend/scripts/generate-openapi.mjs. Do not edit.\n// Source-SHA256: ${hash}\n\n${astToString(await openapiTS(source))}`;
if (process.argv.includes("--check")) {
  if (generated !== await readFile(output, "utf8")) {
    console.error("OpenAPI client drift: run pnpm generate:api and commit the generated contract.");
    process.exitCode = 1;
  }
} else {
  await writeFile(output, generated);
}
