import {chromium,expect,type BrowserContext,type Page,type Locator} from "@playwright/test";
import {readFile,writeFile,mkdir,stat} from "node:fs/promises";
import {existsSync} from "node:fs";
import {resolve} from "node:path";
import {randomUUID,createHash} from "node:crypto";
import assert from "node:assert/strict";
import {catalogReader} from "../lib/catalog-api.js";
import {redactVisualEvidence} from "./visual-privacy.mjs";

const origin=process.env.MANAGE_BASE_URL,runtimePath=process.env.MANAGE_RUNTIME_EVIDENCE,credentialPath=process.env.VISUAL_ADMIN_CREDENTIALS_FILE;
if(!origin||!runtimePath||!credentialPath)throw new Error("MANAGE_BASE_URL, MANAGE_RUNTIME_EVIDENCE and private VISUAL_ADMIN_CREDENTIALS_FILE are required");
const runtime=JSON.parse(await readFile(runtimePath,"utf8"));
if(!/^admin_review_forms_/.test(runtime.database)||process.env.MANAGE_ALLOW_DISPOSABLE_MUTATIONS!=="true")throw new Error("Browser writes require an explicitly designated disposable forms database");
const fixtureSha256=runtime.fixture?createHash("sha256").update(await readFile(runtime.fixture)).digest("hex"):null;
const buildId=process.env.NEXT_DIST_DIR?(await readFile(resolve(process.env.NEXT_DIST_DIR,"BUILD_ID"),"utf8")).trim():null;
if(((await stat(credentialPath)).mode&0o077)!==0)throw new Error("Credentials file must be private (0600)");
const credentials=JSON.parse(await readFile(credentialPath,"utf8"));
const password=credentials.TARGET_ADMIN_PASSWORD,admin=credentials.TARGET_ADMIN_USERNAME;
if(!password||!admin)throw new Error("Target administrator credentials are missing");
const roles={admin,editor:process.env.MANAGE_EDITOR_USERNAME??"visual-editor",viewer:process.env.MANAGE_VIEWER_USERNAME??"visual-viewer"};
const auth=(username:string)=>`Basic ${Buffer.from(`${username}:${password}`).toString("base64")}`;
const reader=catalogReader(new Headers({authorization:auth(admin)}),fetch,runtime.apiBaseUrl);
const output=resolve(process.env.MANAGE_FLOW_OUTPUT??"evidence/manage-flow");await mkdir(output,{recursive:true});
if(existsSync(resolve(output,"report.json")))throw new Error("Evidence already exists; set MANAGE_FLOW_OUTPUT to a fresh directory");
const runId=randomUUID(),suffix=runId.replaceAll("-","").slice(0,12),name=`Browser fixture ${suffix}`,shortName=`UI ${suffix}`;
const browser=await chromium.launch(),contexts:BrowserContext[]=[],checks:{name:string;passed:boolean;error?:string}[]=[];
let currentPage:Page|undefined,institutionId:number|undefined;
const submissions:{action:string|null;status:number;origin:string|null;host:string|null;fetchSite:string|null}[]=[];
const secrets=[password,...Object.values(roles).map((username)=>auth(username)),...Object.values(roles).map((username)=>Buffer.from(`${username}:${password}`).toString("base64"))];
async function pageFor(role:keyof typeof roles){const context=await browser.newContext({viewport:{width:1440,height:900},locale:"ru-RU",httpCredentials:{username:roles[role],password,origin:new URL(origin!).origin}});contexts.push(context);const page=await context.newPage();currentPage=page;return page;}
async function open(page:Page){currentPage=page;const response=await page.goto(new URL("/manage",origin!).toString(),{waitUntil:"networkidle"});assert.equal(response?.status(),200);assert.match(response?.headers()["cache-control"]??"",/no-store/);await expect(page.getByRole("heading",{name:"Управление каналами",exact:true})).toBeVisible();}
async function submit(page:Page,form:Locator,expectedStatus=303){currentPage=page;const action=await form.getAttribute("action");const [response]=await Promise.all([page.waitForResponse((response)=>response.request().method()==="POST"&&new URL(response.url()).pathname===action),form.getByRole("button").click()]);const sent=await response.request().allHeaders();submissions.push({action,status:response.status(),origin:sent.origin??null,host:sent.host??null,fetchSite:sent["sec-fetch-site"]??null});assert.equal(response.status(),expectedStatus);assert.match(response.headers()["cache-control"]??"",/no-store/);await page.waitForLoadState("networkidle");}
async function institution(){const row=(await reader.institutions()).find((item)=>item.legacyId===institutionId);assert.ok(row,"Created institution remains readable through the real catalog API");return row;}
async function check(name:string,run:()=>Promise<void>){try{await run();checks.push({name,passed:true});console.log(`${name}: PASS`);}catch(error){checks.push({name,passed:false,error:redactVisualEvidence(error instanceof Error?error.message:String(error),secrets)});throw error;}}
let failure:string|undefined;
try{
  await check("anonymous challenge and no-store",async()=>{const response=await fetch(new URL("/manage",origin));assert.equal(response.status,401);assert.equal(response.headers.get("cache-control"),"no-store");assert.deepEqual(await response.json(),{detail:"Not authenticated"});});
  const viewer=await pageFor("viewer"),editor=await pageFor("editor"),administrator=await pageFor("admin");
  await check("viewer/editor/admin server capabilities",async()=>{for(const [role,page] of [["viewer",viewer],["editor",editor],["admin",administrator]] as const){await open(page);await expect(page.locator('[data-testid="institution-create"] input[name="name"]')).toBeEnabled({enabled:role!=="viewer"});await expect(page.getByRole("button",{name:"Удалить",exact:true}).first()).toBeEnabled({enabled:role==="admin"});const html=await page.content();assert.ok(!html.includes(password)&&!html.includes(auth(roles[role])));}});
  await check("CSRF cookie and HTML tokens remain stable across authenticated reloads",async()=>{currentPage=editor;const before=(await editor.context().cookies()).find((cookie)=>cookie.name==="MRANKED-MANAGE-CSRF");assert.ok(before,"Administrative CSRF cookie exists");assert.equal(before.httpOnly,true);assert.equal(before.sameSite,"Strict");assert.equal(before.path,"/manage");const tokens=await editor.locator('input[name="csrf_token"]').evaluateAll((nodes)=>nodes.map((node)=>(node as HTMLInputElement).value));assert.ok(tokens.length>0&&tokens.every((token)=>token===before.value),"Every server-rendered form matches the cookie");await open(editor);const after=(await editor.context().cookies()).find((cookie)=>cookie.name==="MRANKED-MANAGE-CSRF");assert.ok(after?.value===before.value,"Basic-authenticated reload preserves the established CSRF token");});
  await check("editor creates institution through HTML form",async()=>{const form=editor.getByTestId("institution-create");await form.locator('[name="name"]').fill(name);await form.locator('[name="short_name"]').fill(shortName);await submit(editor,form);await expect(editor.getByRole("status")).toHaveText("Вуз добавлен.");const row=(await reader.institutions()).find((item)=>item.name===name);assert.ok(row);institutionId=row.legacyId;assert.equal(row.shortName,shortName);});
  await check("editor renames institution with optimistic version",async()=>{const form=editor.locator(`form[action="/manage/institutions/${institutionId}"]`);await form.locator("..").locator("summary").click();await form.locator('[name="name"]').fill(`${name} updated`);await submit(editor,form);assert.equal((await institution()).name,`${name} updated`);});
  await check("matrix creates all four platforms without dropping selections",async()=>{await editor.locator("#matrixInstitution").selectOption(String(institutionId));const form=editor.locator("#accountMatrix");for(const [field,value] of Object.entries({telegram:`@ui_${suffix}`,vk:`https://vk.com/ui_${suffix}`,max_account:`https://max.ru/ui_${suffix}`,rutube:`https://rutube.ru/channel/${suffix}`}))await form.locator(`[name="${field}"]`).fill(value);await submit(editor,form);assert.deepEqual((await institution()).accounts.map((account)=>account.platform).sort(),["max","rutube","telegram","vk"]);});
  await check("existing matrix updates retain account identities",async()=>{const before=await institution();await editor.locator("#matrixInstitution").selectOption(String(institutionId));await submit(editor,editor.locator("#accountMatrix"));const after=await institution();assert.deepEqual(after.accounts.map((row)=>row.id).sort(),before.accounts.map((row)=>row.id).sort());});
  await check("MAX native ID disclosure submits and persists",async()=>{const account=(await institution()).accounts.find((row)=>row.platform==="max")!;const form=editor.locator(`form[action="/manage/platform-accounts/${account.legacyId}/native-id"]`);await form.locator("..").locator("summary").click();await form.locator('[name="native_id"]').fill("-1009876543210");await submit(editor,form);assert.equal((await institution()).accounts.find((row)=>row.id===account.id)?.nativeId,"-1009876543210");});
  await check("disable preserves account and stale browser receives 409",async()=>{const account=(await institution()).accounts.find((row)=>row.platform==="vk")!;await open(administrator);await submit(editor,editor.locator(`form[action="/manage/platform-accounts/${account.legacyId}/disable"]`));assert.equal((await institution()).accounts.find((row)=>row.id===account.id)?.enabled,false);await submit(administrator,administrator.locator(`form[action="/manage/platform-accounts/${account.legacyId}/disable"]`),409);assert.equal((await institution()).accounts.find((row)=>row.id===account.id)?.enabled,false);});
  await check("enable restores collection through browser form",async()=>{const account=(await institution()).accounts.find((row)=>row.platform==="vk")!;await submit(editor,editor.locator(`form[action="/manage/platform-accounts/${account.legacyId}/enable"]`));assert.equal((await institution()).accounts.find((row)=>row.id===account.id)?.enabled,true);});
  await check("invalid CSRF is rejected before mutation",async()=>{const before=await institution(),account=before.accounts.find((row)=>row.platform==="vk")!;const form=editor.locator(`form[action="/manage/platform-accounts/${account.legacyId}/disable"]`);await form.locator('[name="csrf_token"]').evaluate((element)=>(element as HTMLInputElement).value="invalid-test-token");await submit(editor,form,403);const after=(await institution()).accounts.find((row)=>row.id===account.id)!;assert.equal(after.enabled,true);assert.equal(after.rowVersion,account.rowVersion);});
  await check("delete cancellation sends no mutation",async()=>{await open(administrator);const account=(await institution()).accounts.find((row)=>row.platform==="vk")!;let posts=0;const listener=(request:{method:()=>string})=>{if(request.method()==="POST")posts++;};administrator.on("request",listener);await administrator.locator(`form[action="/manage/platform-accounts/${account.legacyId}/delete"] button`).click();await administrator.getByRole("alertdialog").getByRole("button",{name:"Отмена"}).click();await administrator.waitForTimeout(150);administrator.off("request",listener);assert.equal(posts,0);assert.ok((await institution()).accounts.some((row)=>row.id===account.id));});
  await check("administrator confirms deletion and API removes account",async()=>{const account=(await institution()).accounts.find((row)=>row.platform==="vk")!;await administrator.locator(`form[action="/manage/platform-accounts/${account.legacyId}/delete"] button`).click();await Promise.all([administrator.waitForURL(/platform_status=account-deleted/),administrator.getByRole("alertdialog").getByRole("button",{name:"Удалить",exact:true}).click()]);assert.ok(!(await institution()).accounts.some((row)=>row.id===account.id));await expect(administrator.getByRole("status")).toHaveText("Аккаунт и собранные по нему данные удалены.");});
  if(process.env.MANAGE_MRATING_OFFLINE_FIXTURE==="true")await check("offline MRating failure remains explicit in UI",async()=>{await open(editor);await submit(editor,editor.locator('form[action="/manage/m-rating/update"]'));await expect(editor.getByText(/Не удалось обновить М‑Рейтинг:/)).toBeVisible();});
}catch(error){failure=redactVisualEvidence(error instanceof Error?error.message:String(error),secrets);if(currentPage){const csrf=await currentPage.locator('input[name="csrf_token"]').evaluateAll((nodes)=>nodes.map((node)=>(node as HTMLInputElement).value)).catch(()=>[]);await writeFile(resolve(output,"failure.dom.html"),redactVisualEvidence(await currentPage.content(),[...secrets,...csrf]));await currentPage.screenshot({path:resolve(output,"failure.png"),fullPage:false});}}
finally{await Promise.all(contexts.map((context)=>context.close()));await browser.close();}
await writeFile(resolve(output,"report.json"),JSON.stringify({generatedAt:new Date().toISOString(),runId,origin,buildId,runtime:{path:runtimePath,database:runtime.database,apiBaseUrl:runtime.apiBaseUrl,pid:runtime.pid,jarSha256:runtime.jarSha256,schemaVersion:runtime.schemaVersion,fixtureSha256},scope:"Actual browser forms against a dedicated disposable database; each successful mutation is verified through the real generated catalog API. Frozen visual/performance database is not used.",institutionId,checks,submissions,gate:failure?"NO-GO":"PASS",failure},null,2)+"\n");
if(failure){console.error(failure);process.exitCode=1;}
